name: Deploy transcribe to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact (avoid deprecated internals)
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: transcribe
          overwrite: true

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1


