name: Deploy transcribe to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        # use v2 which depends on the newer upload-artifact v4 internals
        uses: actions/upload-pages-artifact@v2
        with:
          path: transcribe

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1


